### ISSUE TITLE
docs/demo

### ISSUE THREAD

**Issue by decarlof** [wavepy/wavepy#23]
@wcgrizolli readthedocs give an error building the [example](http://wavepy.readthedocs.io/en/latest/source/demo.html) because 

> speckleAnalyses.py
> speckleAnalyses_postProcessing.py

are missing from the repository. These are supposed to be in wavepy/doc/demo/ folder that was deleted in Feb 2017. Let me know if you want to keep these examples and I will restore the one from November 2016 at [3a353...](https://github.com/wavepy/wavepy/tree/3a353762578c34d2ef17d8c828f1a840bd77567d/doc) unless you have a newer version.

If you agree I will also move the wavepy/examples to wavepy/doc/demo and have these appear in the docs under [example](http://wavepy.readthedocs.io/en/latest/source/demo.html) and delete the [.gitignore](https://github.com/wavepy/wavepy/blob/master/doc/.gitignore) located in the doc folder. This is excluding /demo/ so it could be the reason this folder is gone. In any case there should be only one .gitignore in the project top folder.

**Comment by wcgrizolli** [comment]
@decarlof My goal was to move the examples to the main directory, in order to highlight that they exist. If this is not good practice, you can move they to doc/demo/, but personally I prefer if we keep this way. I have no problem changing the name from 'examples' to 'demo' though.

In any case we need to fix the links. I added the speckle examples again. Can you fix the links in the documentation?

**Comment by decarlof** [comment]
@wcgrizolli both practices are OK. I will fix the links.
